# Generated by Django 5.1.15 on 2026-06-23 23:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True)),
                ('room_type', models.CharField(choices=[('CCMN', 'Chung cu mini'), ('CCDV', 'Can ho dich vu'), ('HOUSE', 'Nha nguyen can')], max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_area', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('short_description', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='room-thumbnails/')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('HIDDEN', 'Hidden')], default='AVAILABLE', max_length=20)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('commission_base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('internal_note', models.TextField(blank=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='rooms', to='locations.amenity')),
                ('area_range', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='locations.arearange')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='locations.city')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_rooms', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='locations.ward')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='room-images/')),
                ('image_url', models.URLField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.room')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['status', 'room_type'], name='rooms_room_status_69ac4d_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['city', 'ward'], name='rooms_room_city_id_8ca8b0_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['price'], name='rooms_room_price_a62835_idx'),
        ),
    ]
