# Generated by Codex on 2026-07-02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="deposit_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name="room",
            name="electricity_price_per_kwh",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name="room",
            name="water_price_per_person",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name="room",
            name="service_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
