# Generated by Django 5.1.15 on 2026-07-15 08:41

import apps.rooms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_workflow_deposit_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomimage',
            name='media_type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], default='IMAGE', max_length=10),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=apps.rooms.models.room_media_upload_to),
        ),
    ]
