# Generated by Django 5.1.15 on 2026-07-15 09:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_roomimage_media_type_alter_roomimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='water_billing_type',
            field=models.CharField(choices=[('PER_PERSON', 'Per person'), ('PER_CUBIC_METER', 'Per cubic meter')], default='PER_PERSON', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='water_price_per_cubic_meter',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
