# Generated by Django 5.1.15 on 2026-07-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_room_building_code_and_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomimage',
            name='label',
            field=models.CharField(blank=True, choices=[('OVERVIEW', 'Toàn cảnh'), ('SLEEPING_AREA', 'Góc ngủ'), ('KITCHEN', 'Bếp'), ('BATHROOM', 'WC'), ('BALCONY', 'Ban công'), ('VIDEO_TOUR', 'Video tham quan'), ('OTHER', 'Khác')], max_length=24),
        ),
    ]
