# Generated by Django 5.1.15 on 2026-07-19 12:16

import re
import unicodedata

from django.db import migrations, models


ROOM_TYPE_LABELS = {
    "CCMN": "Chung c\u01b0 mini",
    "CCDV": "C\u0103n h\u1ed9 d\u1ecbch v\u1ee5",
    "HOUSE": "Nh\u00e0 nguy\u00ean c\u0103n",
}


def normalize_search_text(*values):
    text = " ".join(str(value or "") for value in values)
    decomposed = unicodedata.normalize("NFD", unicodedata.normalize("NFKC", text))
    text = "".join(char for char in decomposed if unicodedata.category(char) != "Mn")
    text = text.replace("\u0111", "d").replace("\u0110", "D").casefold()
    return re.sub(r"[^a-z0-9]+", " ", text).strip()


def populate_room_search_and_media_labels(apps, _schema_editor):
    Room = apps.get_model("rooms", "Room")
    RoomImage = apps.get_model("rooms", "RoomImage")

    rooms = list(Room.objects.select_related("city", "ward", "room_subtype").all())
    for room in rooms:
        room.search_document = normalize_search_text(
            room.title,
            ROOM_TYPE_LABELS.get(room.room_type, room.room_type),
            room.room_subtype.name if room.room_subtype_id else "",
            room.city.name if room.city_id else "",
            room.ward.name if room.ward_id else "",
            room.address,
            room.short_description,
            room.description,
        )
    if rooms:
        Room.objects.bulk_update(rooms, ["search_document"], batch_size=500)

    media_items = list(RoomImage.objects.order_by("room_id", "sort_order", "id"))
    rooms_with_overview = set(
        RoomImage.objects.filter(label="OVERVIEW").values_list("room_id", flat=True)
    )
    changed = []
    for media in media_items:
        if media.label:
            continue
        if media.media_type == "VIDEO":
            media.label = "VIDEO_TOUR"
        elif media.room_id not in rooms_with_overview:
            media.label = "OVERVIEW"
            rooms_with_overview.add(media.room_id)
        else:
            media.label = "OTHER"
        changed.append(media)
    if changed:
        RoomImage.objects.bulk_update(changed, ["label"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_room_media_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='hero_eligible',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='search_document',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.RunPython(populate_room_search_and_media_labels, migrations.RunPython.noop),
    ]
