# Generated by Django 5.1.15 on 2026-06-23 23:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('VIEWED', 'Viewed'), ('MOVED_IN', 'Moved in'), ('NOT_MOVED_IN', 'Not moved in'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=20)),
                ('saler_note', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField()),
                ('moved_in_at', models.DateTimeField(blank=True, null=True)),
                ('is_commission_counted', models.BooleanField(default=False)),
                ('estimated_commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viewing_requests', to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viewing_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'room', 'status'], name='viewing_req_user_id_ddb69f_idx'), models.Index(fields=['status', 'created_at'], name='viewing_req_status_39c5c2_idx')],
            },
        ),
    ]
