# Generated by Codex on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewing_requests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="viewingrequest",
            name="preferred_viewing_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="viewingrequest",
            name="preferred_viewing_time_slot",
            field=models.CharField(
                blank=True,
                choices=[
                    ("morning", "Morning, 9:00 - 12:00"),
                    ("afternoon", "Afternoon, 12:00 - 16:00"),
                    ("evening", "Evening, 16:00 - 19:00"),
                ],
                max_length=20,
            ),
        ),
    ]
