# Generated by Django 5.1.15 on 2026-06-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewing_requests', '0002_viewingrequest_preferred_viewing_window'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewingrequest',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
