# Generated by Django 5.1.15 on 2026-06-28 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        ('viewing_requests', '0003_alter_viewingrequest_confirmed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='viewingrequest',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viewingrequest',
            name='appointment_time_slot',
            field=models.CharField(blank=True, choices=[('morning', 'Morning, 9:00 - 12:00'), ('afternoon', 'Afternoon, 12:00 - 16:00'), ('evening', 'Evening, 16:00 - 19:00')], max_length=20),
        ),
        migrations.AddField(
            model_name='viewingrequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_viewing_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='viewingrequest',
            name='next_follow_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RoomLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('move_in_at', models.DateTimeField()),
                ('move_out_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ENDED', 'Ended')], default='ACTIVE', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='rooms.room')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to=settings.AUTH_USER_MODEL)),
                ('viewing_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lease', to='viewing_requests.viewingrequest')),
            ],
            options={
                'ordering': ('-move_in_at',),
                'indexes': [models.Index(fields=['room', 'status'], name='viewing_req_room_id_4bb445_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('room',), name='unique_active_lease_per_room')],
            },
        ),
        migrations.CreateModel(
            name='ViewingRequestActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewing_request_activities', to=settings.AUTH_USER_MODEL)),
                ('viewing_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='viewing_requests.viewingrequest')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['viewing_request', 'created_at'], name='viewing_req_viewing_f1160a_idx')],
            },
        ),
    ]
