# Generated by Django 5.1.15 on 2026-07-23 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewing_requests', '0006_viewingrequest_appointment_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandlordNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('NEW_VIEWING_REQUEST', 'New viewing request')], max_length=40)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_notifications', to=settings.AUTH_USER_MODEL)),
                ('viewing_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_notifications', to='viewing_requests.viewingrequest')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['recipient', 'read_at', 'created_at'], name='landlord_notification_feed_idx')],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'viewing_request', 'type'), name='unique_landlord_notification_event')],
            },
        ),
    ]
