# Generated by Django 5.1.15 on 2026-06-23 23:41

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20, validators=[apps.common.validators.validate_vietnamese_phone])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('READ', 'Read'), ('HANDLED', 'Handled')], default='NEW', max_length=20)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='contacts_co_status_bc1de3_idx')],
            },
        ),
    ]
