# Generated by Django 5.1.15 on 2026-07-19 12:16

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contactmessage_admin_note_contactmessage_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[apps.common.validators.validate_vietnamese_phone]),
        ),
    ]
