import type { Config } from "tailwindcss";
import plugin from "tailwindcss/plugin";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "rgb(var(--surface-container-low) / <alpha-value>)",
        "on-secondary-fixed": "rgb(var(--on-secondary-fixed) / <alpha-value>)",
        "on-tertiary": "rgb(var(--on-tertiary) / <alpha-value>)",
        "primary-fixed": "rgb(var(--primary-fixed) / <alpha-value>)",
        "tertiary-container": "rgb(var(--tertiary-container) / <alpha-value>)",
        "inverse-on-surface": "rgb(var(--inverse-on-surface) / <alpha-value>)",
        secondary: "rgb(var(--secondary) / <alpha-value>)",
        "on-primary-fixed-variant": "rgb(var(--on-primary-fixed-variant) / <alpha-value>)",
        primary: "rgb(var(--primary) / <alpha-value>)",
        "secondary-fixed-dim": "rgb(var(--secondary-fixed-dim) / <alpha-value>)",
        "surface-container-high": "rgb(var(--surface-container-high) / <alpha-value>)",
        "on-tertiary-fixed": "rgb(var(--on-tertiary-fixed) / <alpha-value>)",
        "on-secondary": "rgb(var(--on-secondary) / <alpha-value>)",
        "primary-fixed-dim": "rgb(var(--primary-fixed-dim) / <alpha-value>)",
        "on-primary": "rgb(var(--on-primary) / <alpha-value>)",
        error: "rgb(var(--error) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--on-surface-variant) / <alpha-value>)",
        "inverse-surface": "rgb(var(--inverse-surface) / <alpha-value>)",
        "primary-container": "rgb(var(--primary-container) / <alpha-value>)",
        "on-error-container": "rgb(var(--on-error-container) / <alpha-value>)",
        "surface-container-highest": "rgb(var(--surface-container-highest) / <alpha-value>)",
        "surface-container-lowest": "rgb(var(--surface-container-lowest) / <alpha-value>)",
        "surface-dim": "rgb(var(--surface-dim) / <alpha-value>)",
        "inverse-primary": "rgb(var(--inverse-primary) / <alpha-value>)",
        "on-error": "rgb(var(--on-error) / <alpha-value>)",
        "tertiary-fixed-dim": "rgb(var(--tertiary-fixed-dim) / <alpha-value>)",
        background: "rgb(var(--background) / <alpha-value>)",
        outline: "rgb(var(--outline) / <alpha-value>)",
        "on-tertiary-container": "rgb(var(--on-tertiary-container) / <alpha-value>)",
        tertiary: "rgb(var(--tertiary) / <alpha-value>)",
        "tertiary-fixed": "rgb(var(--tertiary-fixed) / <alpha-value>)",
        "on-secondary-container": "rgb(var(--on-secondary-container) / <alpha-value>)",
        "on-primary-fixed": "rgb(var(--on-primary-fixed) / <alpha-value>)",
        "on-secondary-fixed-variant": "rgb(var(--on-secondary-fixed-variant) / <alpha-value>)",
        "surface-tint": "rgb(var(--surface-tint) / <alpha-value>)",
        "outline-variant": "rgb(var(--outline-variant) / <alpha-value>)",
        "surface-bright": "rgb(var(--surface-bright) / <alpha-value>)",
        "on-surface": "rgb(var(--on-surface) / <alpha-value>)",
        "error-container": "rgb(var(--error-container) / <alpha-value>)",
        "surface-variant": "rgb(var(--surface-variant) / <alpha-value>)",
        "surface-container": "rgb(var(--surface-container) / <alpha-value>)",
        "secondary-container": "rgb(var(--secondary-container) / <alpha-value>)",
        surface: "rgb(var(--surface) / <alpha-value>)",
        "secondary-fixed": "rgb(var(--secondary-fixed) / <alpha-value>)",
        "on-tertiary-fixed-variant": "rgb(var(--on-tertiary-fixed-variant) / <alpha-value>)",
        "on-background": "rgb(var(--on-background) / <alpha-value>)",
        "on-primary-container": "rgb(var(--on-primary-container) / <alpha-value>)",
        success: "rgb(var(--success) / <alpha-value>)",
        "on-success": "rgb(var(--on-success) / <alpha-value>)",
        "success-container": "rgb(var(--success-container) / <alpha-value>)",
        warning: "rgb(var(--warning) / <alpha-value>)",
        "on-warning": "rgb(var(--on-warning) / <alpha-value>)",
        "warning-container": "rgb(var(--warning-container) / <alpha-value>)",
        "on-warning-container": "rgb(var(--on-warning-container) / <alpha-value>)",
        gold: "rgb(var(--gold) / <alpha-value>)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "64px",
        gutter: "24px",
        unit: "8px",
        "margin-mobile": "16px",
        "container-max": "1280px",
      },
      fontFamily: {
        sans: ["var(--font-body)", "sans-serif"],
        "body-lg": ["var(--font-body)", "sans-serif"],
        button: ["var(--font-body)", "sans-serif"],
        "body-md": ["var(--font-body)", "sans-serif"],
        "label-caps": ["var(--font-body)", "sans-serif"],
        "display-lg": ["var(--font-display)", "serif"],
        "display-lg-mobile": ["var(--font-display)", "serif"],
        "headline-sm": ["var(--font-display)", "serif"],
        "headline-md": ["var(--font-display)", "serif"],
      },
      fontSize: {
        h1: ["48px", { lineHeight: "1.1", letterSpacing: "0", fontWeight: "700" }],
        h2: ["36px", { lineHeight: "1.15", letterSpacing: "0", fontWeight: "700" }],
        h3: ["30px", { lineHeight: "1.2", letterSpacing: "0", fontWeight: "600" }],
        h4: ["24px", { lineHeight: "1.3", letterSpacing: "0", fontWeight: "600" }],
        h5: ["20px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "600" }],
        h6: ["16px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "600" }],
        body: ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        caption: ["12px", { lineHeight: "1.4", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "0", fontWeight: "700" }],
        button: ["14px", { lineHeight: "1.2", letterSpacing: "0", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.3", letterSpacing: "0", fontWeight: "600" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
      boxShadow: {
        low: "0 1px 2px rgba(43,35,30,0.05), 0 1px 3px rgba(43,35,30,0.07)",
        medium: "0 8px 24px rgba(43,35,30,0.08)",
        high: "0 18px 48px rgba(43,35,30,0.12)",
        soft: "0 1px 2px rgba(43,35,30,0.05), 0 1px 3px rgba(43,35,30,0.07)",
        elevated: "0 8px 24px rgba(43,35,30,0.08)",
      },
    },
  },
  plugins: [
    plugin(function({ addUtilities }) {
      addUtilities({
        '.touch-target': {
          minWidth: '44px',
          minHeight: '44px',
          display: 'inline-flex',
          alignItems: 'center',
          justifyContent: 'center',
        },
      });
    }),
  ],
};

export default config;
