# Generated by Django 5.1.15 on 2026-06-28 14:45

from django.db import migrations, models


def migrate_admin_role_to_saler(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(role="ADMIN").update(role="SALER", is_staff=True, is_superuser=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.RunPython(migrate_admin_role_to_saler, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('TENANT', 'Tenant'), ('SALER', 'Saler/Admin')], default='TENANT', max_length=20),
        ),
    ]
