import { NextResponse, type NextRequest } from "next/server";

const cloudinaryHost = "res.cloudinary.com";
const productionApiOrigin = "https://api.forrent.io.vn";
const isProduction = process.env.NODE_ENV === "production";
const unsafeMethods = new Set(["POST", "PUT", "PATCH", "DELETE"]);
// Exact hashes for inline styles generated by Next Image and the App Router announcer.
const styleAttributeSources = [
  "'unsafe-hashes'",
  "'sha256-zlqnbDt84zf1iSefLU/ImC54isoprH/MRiVZGskwexk='",
  "'sha256-ZDrxqUOB4m/L0JWL/+gS52g1CRH0l/qwMhjTw5Z/Fsc='",
  "'sha256-AR6+SB6vXqI9ZnmFvzPZfnCWxZN0sWZ+p+jIVwvhjFk='",
  "'sha256-32t0bJPIyxns/QqsW8RE3JGUERKnHL5RygHBgJvEanc='",
  "'sha256-aqNNdDLnnrDOnTNdkJpYlAxKVJtLt9CtFLklmInuUAE='",
].join(" ");

function nonce() {
  const bytes = new Uint8Array(16);
  crypto.getRandomValues(bytes);
  return btoa(String.fromCharCode(...bytes));
}

function origin(value = productionApiOrigin) {
  try {
    return new URL(value).origin;
  } catch {
    return productionApiOrigin;
  }
}

function optionalOrigin(value?: string) {
  if (!value) return "";
  try {
    return new URL(value).origin;
  } catch {
    return "";
  }
}

function requestOrigin(request: NextRequest) {
  const host = request.headers.get("host");
  const proto = request.headers.get("x-forwarded-proto") || request.nextUrl.protocol.replace(":", "");
  return host ? `${proto}://${host}` : request.nextUrl.origin;
}

function csrfFailure(request: NextRequest) {
  if (!request.nextUrl.pathname.startsWith("/api/") || !unsafeMethods.has(request.method)) {
    return null;
  }

  const originHeader = request.headers.get("origin");
  if (!originHeader) {
    return isProduction ? NextResponse.json({ success: false, message: "Invalid request origin.", errors: {} }, { status: 403 }) : null;
  }

  const allowedOrigins = new Set([
    requestOrigin(request),
    process.env.NEXT_PUBLIC_SITE_URL || "",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
  ]);

  if (!allowedOrigins.has(origin(originHeader))) {
    return NextResponse.json({ success: false, message: "Invalid request origin.", errors: {} }, { status: 403 });
  }

  return null;
}

export function middleware(request: NextRequest) {
  const blocked = csrfFailure(request);
  if (blocked) {
    return blocked;
  }

  const requestHeaders = new Headers(request.headers);
  const requestNonce = nonce();
  const apiOrigin = origin(process.env.NEXT_PUBLIC_API_BASE_URL);
  const sentryOrigin = optionalOrigin(process.env.NEXT_PUBLIC_SENTRY_DSN);
  const localApiSources = isProduction ? [] : ["http://localhost:8000", "http://127.0.0.1:8000", "http://backend:8000"];
  const scriptSources = [`'self'`, `'nonce-${requestNonce}'`, "'strict-dynamic'", ...(!isProduction ? ["'unsafe-eval'"] : [])].join(" ");
  const csp = [
    "default-src 'self'",
    `script-src ${scriptSources}`,
    `style-src 'self' 'nonce-${requestNonce}' https://fonts.googleapis.com`,
    `style-src-attr ${styleAttributeSources}`,
    "font-src 'self' https://fonts.gstatic.com",
    `img-src 'self' data: blob: https://${cloudinaryHost} ${apiOrigin} ${localApiSources.join(" ")}`,
    `connect-src 'self' ${apiOrigin} ${sentryOrigin} ${localApiSources.join(" ")}`,
    "object-src 'none'",
    "base-uri 'self'",
    "frame-ancestors 'none'",
    "form-action 'self'",
  ].join("; ");

  requestHeaders.set("x-nonce", requestNonce);
  requestHeaders.set("Content-Security-Policy", csp);

  const response = NextResponse.next({ request: { headers: requestHeaders } });
  response.headers.set("Content-Security-Policy", csp);
  return response;
}

export const config = {
  matcher: ["/((?!_next/static|_next/image|favicon.ico|robots.txt|sitemap.xml).*)"],
};
