import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f7f3f2",
        "on-secondary-fixed": "#1b1c1b",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#e5e2e1",
        "tertiary-container": "#1c1b1a",
        "inverse-on-surface": "#f4f0ef",
        secondary: "#5e5e5d",
        "on-primary-fixed-variant": "#474746",
        primary: "#000000",
        "secondary-fixed-dim": "#c8c6c4",
        "surface-container-high": "#ebe7e6",
        "on-tertiary-fixed": "#1c1b1a",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#c8c6c5",
        "on-primary": "#ffffff",
        error: "#ba1a1a",
        "on-surface-variant": "#444748",
        "inverse-surface": "#313030",
        "primary-container": "#1c1b1b",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e5e2e1",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#ddd9d8",
        "inverse-primary": "#c8c6c5",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#cac6c4",
        background: "#fdf8f8",
        outline: "#747878",
        "on-tertiary-container": "#868382",
        tertiary: "#000000",
        "tertiary-fixed": "#e6e2df",
        "on-secondary-container": "#636361",
        "on-primary-fixed": "#1c1b1b",
        "on-secondary-fixed-variant": "#464746",
        "surface-tint": "#5f5e5e",
        "outline-variant": "#c4c7c7",
        "surface-bright": "#fdf8f8",
        "on-surface": "#1c1b1b",
        "error-container": "#ffdad6",
        "surface-variant": "#e5e2e1",
        "surface-container": "#f1edec",
        "secondary-container": "#e1dfdd",
        surface: "#fdf8f8",
        "secondary-fixed": "#e4e2e0",
        "on-tertiary-fixed-variant": "#484645",
        "on-background": "#1c1b1b",
        "on-primary-container": "#858383",
        gold: "#D4AF37",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-desktop": "64px",
        gutter: "24px",
        unit: "8px",
        "margin-mobile": "16px",
        "container-max": "1280px",
      },
      fontFamily: {
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "display-lg": ["var(--font-playfair)", "serif"],
        button: ["var(--font-inter)", "sans-serif"],
        "headline-sm": ["var(--font-playfair)", "serif"],
        "headline-md": ["var(--font-playfair)", "serif"],
        "display-lg-mobile": ["var(--font-playfair)", "serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "label-caps": ["var(--font-inter)", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "0", fontWeight: "700" }],
        button: ["14px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-sm": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
      boxShadow: {
        soft: "0 4px 20px rgba(26,26,26,0.04)",
        elevated: "0 12px 32px rgba(26,26,26,0.08)",
      },
    },
  },
  plugins: [],
};

export default config;
