export {
  WarningCircle as AlertCircle,
  Warning as AlertTriangle,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  ChartBar as BarChart3,
  Bed as BedDouble,
  Buildings as Building2,
  Calculator,
  CalendarCheck,
  CalendarDots as CalendarClock,
  Calendar as CalendarDays,
  Car,
  Check,
  CheckCircle,
  CheckCircle as CheckCircle2,
  CaretDown as ChevronDown,
  CaretLeft as ChevronLeft,
  CaretRight as ChevronRight,
  CurrencyCircleDollar as CircleDollarSign,
  Clock,
  Clock as Clock3,
  CookingPot,
  DoorOpen,
  Drop as Droplets,
  Barbell as Dumbbell,
  Bell,
  Eye,
  EyeSlash as EyeOff,
  FileText,
  Question as HelpCircle,
  House as Home,
  House,
  Image as ImageIcon,
  ImageBroken as ImageOff,
  Tray as Inbox,
  Info,
  Key as KeyRound,
  CircleNotch as LoaderCircle,
  Lock,
  SignOut as LogOut,
  Envelope as Mail,
  MapPin,
  List as Menu,
  ChatCircle as MessageCircle,
  ChatText as MessageSquareText,
  Newspaper,
  SidebarSimple as PanelLeftClose,
  SidebarSimple as PanelLeftOpen,
  CarProfile as ParkingCircle,
  PencilSimple as Pencil,
  Phone,
  PhoneCall,
  Play,
  Plus,
  Receipt as ReceiptText,
  ArrowCounterClockwise as RefreshCcw,
  ArrowCounterClockwise as RefreshCw,
  Ruler,
  FloppyDisk as Save,
  MagnifyingGlass as Search,
  MagnifyingGlassMinus as SearchX,
  PaperPlaneTilt as Send,
  Gear as Settings,
  ShieldCheck,
  Shower as ShowerHead,
  Sparkle as Sparkles,
  Trash as Trash2,
  TrendUp as TrendingUp,
  UserGear as UserCog,
  UserCircle as UserRound,
  UsersThree as UsersRound,
  VideoCamera as Video,
  Wallet as WalletCards,
  WashingMachine,
  Waves,
  WifiHigh as Wifi,
  Wind,
  Wine,
  X,
  Lightning as Zap,
} from "@phosphor-icons/react/ssr";
